# Use the official Deno image as the base image
FROM denoland/deno:alpine-2.4.2

# Set default architecture to a linux-x86_64-compatible target for the container
ARG ARCH=x86_64-unknown-linux-gnu

# Create working directory
WORKDIR /app

# Copy source
COPY . .

# Compile the main app for development
RUN deno cache server/main.ts

# Expose the port the server will run on
EXPOSE 8080

# Command to run the development server
CMD ["run", "--watch", "--allow-all", "server/main.ts"]