name: Prepare runner environment
description: Prepares the runner environment

inputs:
  checkout:
    default: "true"
    description: "Checkout repo"
  setup-qemu:
    default: "true"
    description: "Set up QEMU"
  setup-buildx:
    default: "true"
    description: "Set up Docker Buildx"
  platforms:
    default: "linux/amd64,linux/arm64"
    description: "Platforms for QEMU"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    - name: Set up QEMU
      if: ${{ inputs['setup-qemu'] == 'true' }}
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.platforms }}
        cache-image: true

    - name: Set up Docker Buildx
      if: ${{ inputs['setup-buildx'] == 'true' }}
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.platforms }}
        install: true
        cache-binary: true
        cleanup: true