name: Build and push Docker image

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & push (${{ matrix.tag }})
    runs-on: ubuntu-latest
    concurrency:
      group: docker-build-${{ github.ref }}-${{ matrix.tag }}
      cancel-in-progress: false
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            arch: x86_64-unknown-linux-gnu
            tag: amd64
          - platform: linux/arm64
            arch: aarch64-unknown-linux-gnu
            tag: arm64

    steps:
      - name: Prepare runner environment
        uses: realfredlai/gotracksuit-sre-test/.github/actions/prepare-runner@main
        with:
          platforms: ${{ matrix.platform }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            ARCH=${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/suit-tracker:latest-${{ matrix.tag }}
            ghcr.io/${{ github.repository_owner }}/suit-tracker:${{ github.sha }}-${{ matrix.tag }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Image metadata
        run: |
          echo "Pushed images:"
          echo "  ghcr.io/${{ github.repository_owner }}/suit-tracker:latest-${{ matrix.tag }}"
          echo "  ghcr.io/${{ github.repository_owner }}/suit-tracker:${{ github.sha }}-${{ matrix.tag }}"
